/* This file is generated by scripts/generate-project-data.mjs. */

export type GeneratedVideoProject = {
  id: string;
  category: "AI 改包" | "实拍作品";
  title: string;
  src: string;
};

export const heroImages = [
  "/projects/tupian/1.png",
  "/projects/tupian/2.png",
  "/projects/tupian/3.png",
  "/projects/tupian/4.png",
  "/projects/tupian/5.png",
  "/projects/tupian/6.png",
  "/projects/tupian/7.png"
] as const;

export const aiGaibaoProjects: readonly GeneratedVideoProject[] = [
  {
    "id": "aigaibao-01",
    "category": "AI 改包",
    "title": "AI 改包 01",
    "src": "/projects/aigaibao/gaibao%20(1).mp4"
  },
  {
    "id": "aigaibao-02",
    "category": "AI 改包",
    "title": "AI 改包 02",
    "src": "/projects/aigaibao/gaibao%20(2).mp4"
  },
  {
    "id": "aigaibao-03",
    "category": "AI 改包",
    "title": "AI 改包 03",
    "src": "/projects/aigaibao/gaibao%20(3).mp4"
  },
  {
    "id": "aigaibao-04",
    "category": "AI 改包",
    "title": "AI 改包 04",
    "src": "/projects/aigaibao/gaibao%20(4).mp4"
  },
  {
    "id": "aigaibao-05",
    "category": "AI 改包",
    "title": "AI 改包 05",
    "src": "/projects/aigaibao/gaibao%20(5).mp4"
  },
  {
    "id": "aigaibao-06",
    "category": "AI 改包",
    "title": "AI 改包 06",
    "src": "/projects/aigaibao/gaibao%20(6).mp4"
  },
  {
    "id": "aigaibao-07",
    "category": "AI 改包",
    "title": "AI 改包 07",
    "src": "/projects/aigaibao/gaibao%20(7).mp4"
  },
  {
    "id": "aigaibao-08",
    "category": "AI 改包",
    "title": "AI 改包 08",
    "src": "/projects/aigaibao/gaibao%20(8).mp4"
  },
  {
    "id": "aigaibao-09",
    "category": "AI 改包",
    "title": "AI 改包 09",
    "src": "/projects/aigaibao/gaibao%20(9).mp4"
  },
  {
    "id": "aigaibao-10",
    "category": "AI 改包",
    "title": "AI 改包 10",
    "src": "/projects/aigaibao/gaibao%20(10).mp4"
  },
  {
    "id": "aigaibao-11",
    "category": "AI 改包",
    "title": "AI 改包 11",
    "src": "/projects/aigaibao/gaibao%20(11).mp4"
  },
  {
    "id": "aigaibao-12",
    "category": "AI 改包",
    "title": "AI 改包 12",
    "src": "/projects/aigaibao/gaibao%20(12).mp4"
  },
  {
    "id": "aigaibao-13",
    "category": "AI 改包",
    "title": "AI 改包 13",
    "src": "/projects/aigaibao/gaibao%20(13).mp4"
  },
  {
    "id": "aigaibao-14",
    "category": "AI 改包",
    "title": "AI 改包 14",
    "src": "/projects/aigaibao/gaibao%20(14).mp4"
  },
  {
    "id": "aigaibao-15",
    "category": "AI 改包",
    "title": "AI 改包 15",
    "src": "/projects/aigaibao/gaibao%20(15).mp4"
  }
];

export const liveActionProjects: readonly GeneratedVideoProject[] = [
  {
    "id": "shipai-01",
    "category": "实拍作品",
    "title": "实拍作品 01",
    "src": "/projects/shipai/shipai%20(1).mp4"
  },
  {
    "id": "shipai-02",
    "category": "实拍作品",
    "title": "实拍作品 02",
    "src": "/projects/shipai/shipai%20(2).mp4"
  },
  {
    "id": "shipai-03",
    "category": "实拍作品",
    "title": "实拍作品 03",
    "src": "/projects/shipai/shipai%20(3).mp4"
  },
  {
    "id": "shipai-04",
    "category": "实拍作品",
    "title": "实拍作品 04",
    "src": "/projects/shipai/shipai%20(4).mp4"
  },
  {
    "id": "shipai-05",
    "category": "实拍作品",
    "title": "实拍作品 05",
    "src": "/projects/shipai/shipai%20(5).mp4"
  },
  {
    "id": "shipai-06",
    "category": "实拍作品",
    "title": "实拍作品 06",
    "src": "/projects/shipai/shipai%20(6).mp4"
  },
  {
    "id": "shipai-07",
    "category": "实拍作品",
    "title": "实拍作品 07",
    "src": "/projects/shipai/shipai%20(7).mp4"
  },
  {
    "id": "shipai-08",
    "category": "实拍作品",
    "title": "实拍作品 08",
    "src": "/projects/shipai/shipai%20(8).mp4"
  }
];

export const videoProjects: readonly GeneratedVideoProject[] = [...aiGaibaoProjects, ...liveActionProjects];
